CREATE DATABASE schedule;

USE schedule;

CREATE TABLE schedule (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '식별자',
    title VARCHAR(100) NOT NULL COMMENT '제목',
    author VARCHAR(20) NOT NULL COMMENT '작성자',
    details TEXT NOT NULL COMMENT '할일',
    password VARCHAR(60) NOT NULL COMMENT '비밀번호',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
);